site_name: Cuadrature

nav:
  - index.md
  - tutorial.md
  - explanation.md
  - reference.md  

theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


